### ISSUE TITLE
XNAT: upload/download button

### ISSUE THREAD

**Issue by KanishkaS** [QIB-Sheffield/WEASEL#29]
On pressing 'cancel' or 'exit' button for 'XNAT login'. The program crashes with the following detail. PS. no attempt was made to download or upload any data.

Traceback (most recent call last):
  File "/Users/kanishkasharma/Documents/GitHub/WEASEL/CoreModules/WEASEL/Menus.py", line 61, in <lambda>
    self.menuItem.triggered.connect(lambda : objFunction(self))
  File "/Users/kanishkasharma/Documents/GitHub/WEASEL/MenuItems/UKRIN-MAPS/XNATapp.py", line 91, in upload
    url = loginDetails[0] # https://test-ukrin.dpuk.org
TypeError: 'NoneType' object is not subscriptable
Abort trap: 6

Activity log:

Login attempt failed for https://test-ukrin.dpuk.org, please make sure your credentials for user j.sousa are correct!

**Comment by JSousa-UoL** [comment]
Hi @KanishkaS, I don't have the most recent version of Weasel and there were significant changes. I'll try to come to this when possible. For now I'm looking at the requirements.txt issue you showed me earlier.

**Comment by KanishkaS** [comment]
No problem. I noticed that it was pointing to the original xnatapp file. I changed that to iBEAt version and weasel crashes also on trying to login with credentials (it might be that the password is incorrect but I would not expect weasel to crash on that).

Traceback (most recent call last):
  File "/Users/kanishkasharma/Documents/GitHub/WEASEL/CoreModules/WEASEL/Menus.py", line 61, in <lambda>
    self.menuItem.triggered.connect(lambda : objFunction(self))
  File "/Users/kanishkasharma/Documents/GitHub/WEASEL/MenuItems/iBEAt/XNATappiBEAt.py", line 26, in download
    with xnat.connect(url, user=username, password=password) as session:
  File "/Users/kanishkasharma/.local/lib/python3.8/site-packages/xnat/__init__.py", line 402, in connect
    logged_in_user = check_auth(requests_session, server=server, user=user, logger=logger)
  File "/Users/kanishkasharma/.local/lib/python3.8/site-packages/xnat/__init__.py", line 93, in check_auth
    raise exceptions.XNATAuthError(message)
xnat.exceptions.XNATAuthError: Could not determine if login was successful!
Abort trap: 6

**Comment by JSousa-UoL** [comment]
The Cancel button is now corrected so it should work fine.
As for your login attempt, there's not much I can say. Double check your credentials and the URL should be "https://(...).ch". Any issues logging in, it might be due to the Python XNAT package: https://xnat.readthedocs.io/en/latest/
Let me know if you managed to make progress on this.

If your XNAT portal is not https but http, then that's a security issue on Switzerland's side

**Comment by KanishkaS** [comment]
The cancel button is still throwing an error: (I have synced from Github before trying this)

Traceback (most recent call last):
  File "/Users/kanishkasharma/Documents/GitHub/WEASEL/CoreModules/WEASEL/Menus.py", line 61, in <lambda>
    self.menuItem.triggered.connect(lambda : objFunction(self))
  File "/Users/kanishkasharma/Documents/GitHub/WEASEL/Pipelines/iBEAt/XNATappiBEAt.py", line 91, in upload
    url = loginDetails[0] #
TypeError: 'NoneType' object is not subscriptable
Abort trap: 6

**Comment by JSousa-UoL** [comment]
It's solved now @KanishkaS. The first time I corrected the bug only in the generic XNATapp, but the XNATiBEAT script needed the same bug correction.

**Comment by KanishkaS** [comment]
Thanks, @JSousa-UoL. It works for the cancel button for the 'download' option but the upload button and exit key still have this issue.

**Comment by JSousa-UoL** [comment]
True, I never wrote these cancel button actions for the upload. It's all done now, hopefully it will work as expected. Bear in mind that if the upload doesn't work as suggested, the scan will go to archive.
I suggest that you create a test project in iBeat XNAT if you want to test and use this for iBeat. It's too risky if you use it on an ongoing project where the site is still acquiring scans

**Comment by plaresmedima** [comment]
Kanishka - let's be VERY careful testing this on the actual iBEAt dataset.
Do not move to the actual iBEAt dataset until you are 1000% sure that
nothing can be accidentally deleted or overwritten. All of this is totally
untested.

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*

**Comment by KanishkaS** [comment]
@JSousa-UoL: The exit button ('red cross') still has the issue. I did not attempt to login but only exited using this option rather than cancel and it throws the following error.

[CRITICAL] Login attempt failed for https://xnat.vital-it.ch, please make sure your credentials for user  are correct!
Traceback (most recent call last):
  File "/Users/kanishkasharma/Documents/GitHub/WEASEL/CoreModules/WEASEL/Menus.py", line 62, in <lambda>
    self.menuItem.triggered.connect(lambda : objFunction(self))
  File "/Users/kanishkasharma/Documents/GitHub/WEASEL/Pipelines/iBEAt/XNATappiBEAt.py", line 22, in download
    with xnat.connect(url, user=username, password=password) as session:
  File "/Users/kanishkasharma/.local/lib/python3.8/site-packages/xnat/__init__.py", line 402, in connect
    logged_in_user = check_auth(requests_session, server=server, user=user, logger=logger)
  File "/Users/kanishkasharma/.local/lib/python3.8/site-packages/xnat/__init__.py", line 66, in check_auth
    raise exceptions.XNATLoginFailedError(message)
xnat.exceptions.XNATLoginFailedError: Login attempt failed for https://xnat.vital-it.ch, please make sure your credentials for user  are correct!
Abort trap: 6

**Comment by JSousa-UoL** [comment]
This specific window close button issue seems to be Mac-only. This exit ('red cross') button is disabled in Windows but it seems that for Mac the action triggered is the same as the OK button.
Unfortunately this cannot be solved now as we're developing Weasel for Weasel. You'll have to use the cancel button in every Weasel application and please avoid the exit button in Mac. It seems this isn't only on XNAT application.
I'm going to close this issue and open a new one with these last two comments
